[build]
  edge_functions = "netlify/edge-functions"

[[edge_functions]]
  # 기존: path = "/ip"
  path = "/*" # 모든 경로에 대해 Edge Function 실행
  function = "log-ip"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "all"
